services:
  worker:
    build: .
    environment:
      TOKEN: $TOKEN
      ENV: $ENV
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      LOGS_CHAT: $LOGS_CHAT
    resources:
      cpu: 1000m
      memory: 3Gi
